### ISSUE TITLE
Grid of Navigation Issue

### ISSUE THREAD

**Issue by gnt36** [gnt36/idm231-gnt36#1]
@philsinatra Below is a link to my CSS and the code I am trying to manipulate to make the 'Home' and '?' in the Navigation of the index page to be on opposite ends (Home on left and ? on right).

[CSS file](https://github.com/gnt36/idm231-gnt36/blob/c5ce7c8872771f7a58b3eb25cb214c986b636742/css/style.css)

`nav {
    position: fixed;
    width: 100%;
    top: 0;
    padding-top: 16px;
    padding-bottom: 16px;

    display: grid;
    justify-items: space-between;
}

a#home {
    color: var(--color-light);
    padding-left: 16px;    
    text-decoration: none;
}

a#help {
    color: var(--color-light);
    padding-right: 16px;
    text-decoration: none;
}`

**Comment by philsinatra** [comment]
There are two issues.

1. Setting `display: grid;` on the `nav` element establishes the `nav` element as the parent element in a grid layout. That means the direct descendants of this element are the child elements in the grid. In this case, `div.topnav` is the grid's only direct descendant child element. This means `div.topnav` will automatically be placed in the first grid cell. You need to work on your HTML structure and set the `display` property to `grid` on the correct parent element.
2. You have not declared the [`grid-column-template`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns) for the grid parent. Without defining the number and size of your grid columns, your grid will default to a single column. 

You should also consider optimizing your HTML structure to be semantically accurate. Consider using an `<ul>` instead of a `<div>` as the parent for the links. In that case, you'd update your structure to `<nav> / <ul> / <li> / <a>`. In that scenario, the `<ul>` is your parent grid element, and the `<li>`s are your grid children.

**Comment by gnt36** [comment]
This was very helpful...thanks!!
